version: '3.8'

services:
  hw_n8n:
    image: n8nio/n8n:latest
    container_name: hw_n8n
    restart: unless-stopped
    ports:
      - "9999:5678"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=dariamish
      - N8N_BASIC_AUTH_PASSWORD=dariamish123
      - N8N_ENCRYPTION_KEY=b3BlbnNzbCBybmQgLW91dCAvdG1wL2VuY3J5cHRpb25rZXkudHh0IDEyOA==
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:9999
      - GENERIC_TIMEZONE=Europe/Moscow
      - PYTHONUNBUFFERED=1
    volumes:
      - hw_n8n_data:/home/node/.n8n

volumes:
  hw_n8n_data: